//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singularity.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_RolePremissionMap
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int PermissionNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int CreateBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public bool Status { get; set; }
    
        public virtual HR_Role HR_Role { get; set; }
    }
}
