//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singularity.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SingularityDbContext : DbContext
    {
        public SingularityDbContext()
            : base("name=SingularityDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HR_Role> HR_Role { get; set; }
        public virtual DbSet<HR_RolePremissionMap> HR_RolePremissionMap { get; set; }
        public virtual DbSet<HR_Settings> HR_Settings { get; set; }
        public virtual DbSet<HR_User> HR_User { get; set; }
    }
}
